[[main]]
 name = "关于"
 pageRef = "about"
 weight = 1

[[main]]
 name = "出版物"
 url = "/Publications/"
 weight = 5

[[main]]
 name = "博客"
 url = "/blogs/"
 weight = 10

[[main]]
 name = "其他"
 weight = 20

[[main]]
 name = "音乐"
 parent = "其他"
 url = "/music/"
 weight = 21

[[main]]
 name = "电影"
 parent = "其他"
 url = "/movies/"
 weight = 22

[[main]]
 name = "标签"
 url = "/tags/"
 weight = 30
